### ISSUE TITLE
Hub failing to launch

### ISSUE THREAD

**Issue by mlcook19** [wifi-tally/wifi-tally#18]
I am having this error getting the hub to run. Any ideas how to solve it?

![wifi tally error](https://user-images.githubusercontent.com/6903305/85930181-81694400-b877-11ea-869f-7fa8e969d0d2.PNG)

**Comment by czenker** [comment]
I just built the current master branch as [v0.1-alpha3](https://github.com/wifi-tally/wifi-tally/releases/tag/v0.1-alpha3). So now the releases and the documentation should match up again.

This version should not show this problem when running production mode, but it now appears in dev mode – so this still needs fixing. But I hope this helps you in the mean time!?

[Background about the error](https://stackoverflow.com/questions/11928013/node-env-is-not-recognized-as-an-internal-or-external-command-operable-comman). Best fix seems to be to [use `cross-env`](https://stackoverflow.com/a/37131308).

**Comment by czenker** [comment]
I just pushed 35a3714. Can someone verify the issue is gone for good?

**Comment by kubikrubik21** [comment]
Confirmation

Hub works fine for me.

Tested v0.1-alpha3 and v0.1-alpha4 on Windows10 64bit

**Comment by czenker** [comment]
This still does not seem to work without running `npm install` before.

**Comment by czenker** [comment]
submitted a different fix
