### ISSUE TITLE
support OBS

### ISSUE THREAD

**Issue by czenker** [wifi-tally/wifi-tally#27]
https://github.com/obsproject/obs-studio

**Comment by DVEntertainment** [comment]
Yes please!

**Comment by marianputsko** [comment]
Yes, please

**Comment by czenker** [comment]
Your voices have been heared. :smile: 

I have added OBS support in the recent commits. It requires the [obs websocket plugin](https://github.com/Palakis/obs-websocket) and allows to track all _scenes_ with a tally light.

Could some of you give it a thorough testing with some real-life setup? A nightly build is available here:

  * https://wifi-tally-nightly.s3.eu-central-1.amazonaws.com/wifi-tally-v0.1.0-21-g389a298.zip
  * https://wifi-tally-nightly.s3.eu-central-1.amazonaws.com/wifi-tally-v0.1.0-21-g389a298.tar.gz
  * https://wifi-tally-nightly.s3.eu-central-1.amazonaws.com/wifi-tally-v0.1.0-21-g389a298.tar.xz

As I have not worked with OBS in production, maybe someone can answer me, if it is enough to only allow to select _scenes_  for the tally lights. It allows for Picture In Picture by embedding scenes into one another. But I am not sure how this is typically set up.

![OBS Studio 26 0 2 (linux) - Profil: Unbenannt - Szenen: Unbenannt_036](https://user-images.githubusercontent.com/264799/99827825-6cf55300-2b5a-11eb-975c-8ed0e3f6667a.png)

Have fun and I hope to hear of your experiences. :movie_camera:

**Comment by DVEntertainment** [comment]
oh my god you are awesome. I'll test it this weekend!

**Comment by czenker** [comment]
@DVEntertainment Any news on this? Did it work out?

**Comment by marianputsko** [comment]
Helo.

I stoppt to use OSB, now I use Wirecast. 

Thank you.

Prajem pekny den, s pozdravom

Marian Putsko, putsko.com, s.r.o.
Zapotocna 959/45
02801 Trstena, Slovakia

Tel. +421905879107
Mail: marian@putsko.com 
------—-----------------------------
www.putsko.com
www.liveproduction.sk
www.selfiebudka.sk
www.knihahosti.sk

**Comment by DVEntertainment** [comment]
> 
> 
> @DVEntertainment Any news on this? Did it work out?

I have used it a couple of times, and it never failed on me! Great implementation!

**Comment by czenker** [comment]
Great to hear! Thanks for testing it.
