### ISSUE TITLE
Include a 0.91" I2C OLED display 

### ISSUE THREAD

**Issue by gumorassi** [wifi-tally/wifi-tally#28]
Is it possible to include a 0.91" I2C OLED display to view Tally's IP address and the name assigned to the device?

**Comment by gumorassi** [comment]
And in the future who knows even the level of WiFI signal

**Comment by czenker** [comment]
Adding the display would almost double the hardware costs of the Tally. :laughing: 

Eventhough I think it would be quite informative I fear that it makes the Tally a bit too complex and distracts the camera operator from the thing they should do (generating video footage).

But if you are willing to invest some time in a Pull Request, I will be happy to include it.
