### ISSUE TITLE
Brightness of Tally can be configured via hub

### ISSUE THREAD

**Issue by czenker** [wifi-tally/wifi-tally#3]

**Comment by DVEntertainment** [comment]
I would love to see it, and i think it shouldn't be too hard (I know nothing about javascript or whatever)
(I'm a programmer (in html and arduino ahahahaha))

**Comment by czenker** [comment]
This is part of [v0.4.0](https://github.com/wifi-tally/wifi-tally/releases/tag/v0.4.0)
