### ISSUE TITLE
Lua: cannot open my-app.lc

### ISSUE THREAD

**Issue by the-observer07** [wifi-tally/wifi-tally#34]
Hey @czenker,

I'm quite new to this, but i used the firmware from 0.1 Alpha4.

Led strip does not light up, onboard led does not light up

**PORT OPEN 115200

Communication with MCU..Got answer! Communication with MCU established.
AutoDetect firmware...

Can't autodetect firmware, because proper answer not received (may be unknown firmware). 
Please, reset module or continue.

NodeMCU 3.0.0.0 built on nodemcu-build.com provided by frightanic.com
	branch: master
	commit: 71a182caa7841cbb478ed90ede526dc881943c80
	release: 
	release DTS: 202001061321
	SSL: false
	build type: float
	LFS: 0x15000
	modules: encoder,file,gpio,net,node,pwm2,struct,tmr,uart,wifi
 build 2020-02-06 20:31 powered by Lua 5.1.4 on SDK 3.0.1-dev(fce080e)
lua: cannot open my-app.lc
stack traceback:
	[C]: in function 'dofile'
	init.lua:1: in main chunk
	[C]: ?
>**

**Comment by czenker** [comment]
Hey @the-observer07.

I'm glad to help. The error looks as if the `my-app.lc` file is not present on NodeMcu. Did you upload all the files ending in `.lc` from the release? It is important to have the files ending in `.lc` (not `.lua`) on the microcontroller. 

Hope this helps. If not: what OS are you using? Which tool chain and what NodeMcu maker? That could help narrowing the issue down.

**Comment by the-observer07** [comment]
@czenker 

I was using windows 10 with pyflasher and esplorer and switched over to using mac os 10.15.5.

I flashed the firmware using NodeMCU.pyflasher and uploaded the files using esplorer and it's now working.

in 0.1 Alpha 4, the files are shown as .lc files; however, in version 0.1 the files all show up as .lua




I've managed to connect it up to the hub and am using a 5vRGB light strip, preview is showing Red and Program is showing Blue on the strip.

**Comment by the-observer07** [comment]
I figured out why, in the code GRB is on pins 2,3,4 but on the assembly instructions it's stated at pins 1,2,3.

**Comment by czenker** [comment]
Glad, that fixes it for you. About the pins: I changed them a few days back to support `WS2812` - so the documentation reflects that already while the releases do not. But every release comes with a snapshot of the documentation in the documentation folder.
