### ISSUE TITLE
HOW TO SET UP THE HUB

### ISSUE THREAD

**Issue by AlexCruz02** [wifi-tally/wifi-tally#39]
**im new to this and idont know how to set up the hub.******

**Comment by czenker** [comment]
Hey @AlexCruz02 

Welcome on Github.

How to install the hub is described in [the Getting Started Guide](https://wifi-tally.github.io/getting-started.html#setting-up-the-hub). Where are you stuck or what does not work?

**Comment by AlexCruz02** [comment]
hi my problem was solved but im having problems uploading the code to the nodemcu im using ESPlorer, and its giving this error
`HÈ110!„ˆëˆJéÿwmou¯{umowu¯»momw¯ou}»­»íëWaiting answer from ESP - Timeout reached. Command aborted.`

**Comment by czenker** [comment]
Hm. I don't have an ESPlorer installation at hand at the moment. According to the internet the error message poped up again recently. It could be related to the new NodeMCU Release that has not been integrated, but some [people report that clicking the FS Info button](https://github.com/nodemcu/nodemcu-firmware/issues/784#issuecomment-613120211) makes the error go away. Might be worth a try. 

If it does not help you could start with a simple Hello World Application to check that the communication between ESPlorer and your microcontroller work. Here are a few examples:

* https://www.electronicwings.com/nodemcu/getting-started-with-nodemcu-using-esplorer
* https://odd-one-out.serek.eu/projects/esp8266-nodemcu-getting-started-hello-world/

**Comment by czenker** [comment]
Closed, because the discussion went stale.
