### ISSUE TITLE
Support NeoPixel RGB leds

### ISSUE THREAD

**Issue by ruudboon** [wifi-tally/wifi-tally#43]
Would be great if we can use NeoPixel led's.

**Comment by czenker** [comment]
You already [can](https://wifi-tally.github.io/tally.html#using-ws2812-neopixel-etc).

Or do you plan something different?

**Comment by ruudboon** [comment]
Cool, totally missed that. Will give it a shot

**Comment by ruudboon** [comment]
Works great.
