### ISSUE TITLE
NFR: Only show live for stage/talent

### ISSUE THREAD

**Issue by ruudboon** [wifi-tally/wifi-tally#44]
Often I don't want to distract my talent and want them to focus on red only. 
Would it be possible to disable the preview for the stage and give the operator only heads up for the preview?

**Comment by czenker** [comment]
With RGB Leds this is easy: Don't connect the green LED. :smile: 

But yes, this should become an option at some point.

If you need a quick fix for now, this is the line to change the logic:

https://github.com/wifi-tally/wifi-tally/blob/389a298332b69e7827ea73f586a1c1794fa06051/tally/src/my-led.lua#L54

**Comment by czenker** [comment]
This is part of [v0.4.0](https://github.com/wifi-tally/wifi-tally/releases/tag/v0.4.0)
