### ISSUE TITLE
Failed to start the hub on a Raspberry Pi 4

### ISSUE THREAD

**Issue by Brunsben** [wifi-tally/wifi-tally#56]
Hi,

i tried to use wifi-tally on a Raspberry Pi 4.

When I execute the command "npm run start" in the Hub I get the following error:

`npm ERR! missing script: start`

What is the reason for this and how do I get it going again? 

greetings

**Comment by czenker** [comment]
Hey Ben.

I have not tried to run the hub on a Raspberry Pi. And the download packages are build for the amd64 architecture. So the Raspi is not really supported at the moment. You should get it to run, though. Execute `npm ci` once and then run `npm run start` again. 

If this does not help, please let me know which version you are running or post the content of the `hub/package.json` file. Also: You might have downloaded the Source Code, not the [actual release](https://github.com/wifi-tally/wifi-tally/releases/download/v0.4.1/wifi-tally-v0.4.1.zip)?

**Comment by Brunsben** [comment]
Hi,
I got the repository via "git clone https://github.com/wifi-tally/wifi-tally/".

When I run npm ci (or npm install) I always get this error:
`Cypress cannot write to the cache directory due to file permissions`
and then a few more errors because the Cypress directory cannot be accessed.
If I then execute "npm run start" I get the error again
`npm ERR! missing script: start`

The content of the package.json is [this](https://pastebin.com/Ezt5VcP7)

**Comment by czenker** [comment]
Ah. That explains the behavior. Please download the [latest release v0.4.1](https://github.com/wifi-tally/wifi-tally/releases/download/v0.4.1/wifi-tally-v0.4.1.zip) and use that instead. You might need to run `npm ci` there too, but apart from that the `start` command should work.

---

Running the hub from the cloned repo is only useful for development. It pulls more libraries that are not needed in production (like Cypress, Typescript, etc) and it boots up very slowly. You can read [hub/Readme.md](https://github.com/wifi-tally/wifi-tally/tree/master/hub#run-the-development-setup) if you are interested how to run it. But if you want to use it in production – the releases are way easier to set up and much faster.

Hope that helps.

**Comment by Brunsben** [comment]
Ah, OK, that seems to work, Thanks
