### ISSUE TITLE
Deactivate LEDs when idle

### ISSUE THREAD

**Issue by Brunsben** [wifi-tally/wifi-tally#59]
Is it possible to deactivate the LEDs when there is no status (not program or preview)? 
They are currently green when idle (idle: new Color(0, 1, 0) )

Or a menu item in the settings where you can configure it?

**Comment by ruudboon** [comment]
In settings you can disable "Shows Idle State"

**Comment by Brunsben** [comment]
Oh, then we must have overturned it, thanks
