### ISSUE TITLE
Not working with Vmix 24.0.0.56

### ISSUE THREAD

**Issue by tobiswdec** [wifi-tally/wifi-tally#60]
Vmix 24.0.0.56 isnt working. But OBS is working fine.

Update: Vmix 23.0.0.68 isnt working neither.

Sometimes the hub shows a video mixer connected, but you can not assing any inputs to tallylights. 
My ESP8266 Tallylight (Kamera1) showing up in hub succesfully.

Config: 
Vmix Version 24.0.0.56
Windows 10 Pro 20H2
Buildnumber: 19042.867

Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz   2.60 GHz, 16GB RAM

npm version
{
  'wifi-tally': '0.4.1',
  npm: '6.14.11',
  ares: '1.16.1',
  brotli: '1.0.9',
  cldr: '37.0',
  icu: '67.1',
  llhttp: '2.1.3',
  modules: '83',
  napi: '7',
  nghttp2: '1.41.0',
  node: '14.16.0',
  openssl: '1.1.1j',
  tz: '2020a',
  unicode: '13.0',
  uv: '1.40.0',
  v8: '8.4.371.19-node.18',
  zlib: '1.2.11'
}

Vmix Config: 
http://192.168.120.168:8088/tally

Web-Controller:
Checked: Port 8088
Username: admin
Password: BLANK/unset
Controller, Shortcuts, Titles, Tally, API: all unchecked, 
Checked: Without Login

Downloaded via https://github.com/wifi-tally/wifi-tally/releases/tag/v0.4.1 as .zip

Powershell Hub Output:
> PS C:\Users\Sellars\Downloads\wifi-tally-v0.4.1\hub> npm run start
>
> wifi-tally@0.4.1 start C:\Users\Sellars\Downloads\wifi-tally-v0.4.1\hub
> node server.js --env=production
>
>Using mixer configuration "vmix"
>Connecting to Vmix at 192.168.120.168:8088
>Serving frontend from directory frontend-static
>Listening for Tallies on 0.0.0.0:7411
>Web Server available on http://localhost:3000
>Connected to vMix
>settings were changed, but no need to restart mixer
>Tally "Kamera1" updated
>Connecting event tally.changed to socket B9RG55KiKgILz4dyAAAA
>Connecting event tally.removed to socket B9RG55KiKgILz4dyAAAA
>Connecting event config.changed.channels to socket B9RG55KiKgILz4dyAAAA
>Connecting event program.changed to socket B9RG55KiKgILz4dyAAAA
>Connecting event tally.logged to socket B9RG55KiKgILz4dyAAAA

tally-settings.ini:
station.ssid=SWD-EC-IT
station.password=******
hub.ip=192.168.120.168
; default is 7411
hub.port=7411
; How you want your Tally to be known
tally.name=Kamera1
; operator.ws2812 = 1
; stage.ws2812    = 2

**Comment by Amenasme** [comment]
the same for me, it doesn't work. web tally doesn't connect

**Comment by ruudboon** [comment]
I tried with 24.0.0.57 and didn't noticed any issues. Could you test with 24.0.0.57 as well?

**Comment by czenker** [comment]
Also works for me on Win10 Build `19042.928` with NodeJS `14.16.1` and vMix `24.0.0.57`. 

The thing that looks strange in your config is the port `8088` used for vMix. Wifi-Tally uses the [TCP Api](https://www.vmix.com/help24/index.htm?TCPAPI.html) on port `8099` – unless you are doing some NATting or port forwarding there is usually no reason to change that. Port `8088` is an HTTP API by vMix that is not used by Wifi-Tally.

**Comment by Amenasme** [comment]
Yeahh, now it works, I was using 8088 port too. With 8099 it works. Thank you! Maybe this thing must be written in the "getting started" section of the website to help people that don't know that. 

I can't connect to atem mini too, I know the ip address of the atem mini but I don't know the port. Where can I read what port the atem mini is using? Thank you

**Comment by tobiswdec** [comment]
closed, it fixed my issue
