### ISSUE TITLE
we need a logo :)

### ISSUE THREAD

**Issue by czenker** [wifi-tally/wifi-tally#8]

**Comment by ruudboon** [comment]
Maybe we can work together on this. https://github.com/ruudboon/tally-blaster

**Comment by czenker** [comment]
Hello and welcome.

> Maybe we can work together on this. https://github.com/ruudboon/tally-blaster

I'd love to see more people and ideas on board. You already have a logo and a case – so consider me envious and intrigued. :laughing: You also have some features implemented that I find quite interesting, like the dimming and a working Access Point configuration. So I am all up for joining forces to give the open source world a reliable and affordable tally light that is just amazing.


As on the logo:

I asked a friend of mine to create a logo, but he is just too busy the last months. The specs I gave him were

* monochrome, so it can be 3d-printed on a (potential) case
* small enough so it can be recognized when used as a browser favicon (32x32 px²)

If you have ideas I am all up for ideas.

**Comment by ruudboon** [comment]
@czenker I got a big production this weekend. But let's have a chat somewhere next week to see if our ideas align. Cheers!

**Comment by czenker** [comment]
@ruudboon I added an email to my profile (or just the one from the commits) and we will find a place to chat.

**Comment by Brunsben** [comment]
I'm not a great graphic artist, but maybe that's an inspiration
![wifi-tally](https://user-images.githubusercontent.com/1269696/111000235-f3d87080-8381-11eb-82a5-c397836ccaa3.png)

**Comment by MrTomek** [comment]
@czenker  Hi guys, I am willing to add something of my own, once I did a tally with HC-12 transmitters (433Mhz) because they have a greater range than

**Comment by ruudboon** [comment]
<img width="908" alt="Screenshot 2021-04-04 at 22 36 17" src="https://user-images.githubusercontent.com/7444246/113520862-2e56b700-9596-11eb-93cd-28a3833d589c.png">

**Comment by czenker** [comment]
I felt that the project deserves something better than the generic "WiFi Tally" name along with the logo. So, say Hi to `vTally`:

<img width="360" alt="vtally-logo" src="https://user-images.githubusercontent.com/264799/118369961-d1dbb400-b5a5-11eb-9f15-6947e562f8b9.png">

**Comment by ruudboon** [comment]
Can you make the new logo available as .svg (vector) for 3d printing?

**Comment by czenker** [comment]
> Can you make the new logo available as .svg (vector) for 3d printing?

https://github.com/wifi-tally/wifi-tally/blob/stream-0.5/art/vtally-logo.svg

Will be on main as soon as `v0.5.0` is merged.
